[window]
title = ""
dimensions.columns = 150
dimensions.lines = 35

[colors.primary]
foreground = "#000000"
background = "#fffff9"

[colors.selection]
background = "#fffacd"
text = "#000000"

[colors.normal]
red = "#ff2400"
green = "#4cbb17"
yellow = "#daa520"

[colors.bright]
yellow = "#daa520"

[colors.cursor]
text = '#f7f7f7'
cursor = '#000000'

[font]
size=12
normal.family = "IBM Plex Mono"
normal.style = "Regular"
bold.style = "Bold"

[mouse]
hide_when_typing = true

[cursor]
style.blinking = "Always"
blink_interval = 500
